@Contactor.Backend_HostAddress = http://localhost:5287

GET {{Contactor.Backend_HostAddress}}/api/Contacts/
Accept: application/json

###

POST {{Contactor.Backend_HostAddress}}/api/Contacts/
Accept: text/plain
Content-Type: application/json

{
    "FirstName": "Benito",
    "LastName": "Palacios Sanchez",
    "Address": "Somewhere Lutry",
    "Email": "benito.palsan@protonmail.com",
    "MobilePhone": "+4177810102030"
}

###

GET {{Contactor.Backend_HostAddress}}/api/Contacts/1
Accept: application/json

###

POST {{Contactor.Backend_HostAddress}}/api/Contacts/1/skills
Content-Type: application/json

{
    "name": "csharp",
    "level": 5
}

###

POST {{Contactor.Backend_HostAddress}}/api/Contacts/1/skills
Content-Type: application/json

{
    "name": "java",
    "level": 3
}

###

DELETE {{Contactor.Backend_HostAddress}}/api/Contacts/1/skills/1

###

GET {{Contactor.Backend_HostAddress}}/api/Skills
Accept: application/json

###
