name: "Deploy"

on:
  workflow_call:
    inputs:
      dotnet_version:
        required: true
        type: string

jobs:
  # TODO #2: Enable when the repo is public
  # upload_doc:
  #   name: "Documentation"
  #   runs-on: "ubuntu-latest"
  #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #   permissions:
  #     pages: write      # to deploy to Pages
  #     id-token: write   # to verify the deployment originates from an appropriate source
  #   # Deploy to the github-pages environment
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v2

  push_artifacts:
    name: "Artifacts"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need full history for version number

      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: "Artifacts"
          path: "./build/artifacts/"

      - name: "Setup .NET SDK"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: "Deploy artifacts"
        run: dotnet run --project build/orchestrator -- --target=Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
